#!/usr/bin/perl

# Meant to take as input the output from svn status
# Only prints lines that do NOT begin with ? or X
#  - i.e., ignore unversioned items (and externals)

# Intended usage: svn status | ignore_unversioned

while (<>) {
  if (!($_ =~ /^(\?|X)/)) {
    print $_;
  }
}
