#!/usr/bin/perl

# Meant to take as input the output from svn status
# Only prints lines that do NOT begin with ? (or ? after some number of spaces)
#  - i.e., ignore unversioned items

# Intended usage: svn status | ignore_unversioned

while (<>) {
  if (!($_ =~ /^\s*\?/)) {
    print $_;
  }
}
