#!/bin/bash

# Bill Sacks
# 3-19-10

# This script converts a variable in a NetCDF file to a specified type.
# It can also change the missing_value and _FillValue attributes for you,
# as well as handling the conversion of other attributes to the specified type, if desired.

function Usage {
    echo "Usage: $0 infile varname outfile type [attname ...]"
    echo "infile: Input NetCDF file name"
    echo "varname: Name of variable to convert to the specified type"
    echo "outfile: Output NetCDF file name"
    echo "type: Desired output type; must be one of 'byte', 'short', 'int', 'float', or 'double'"
    echo "attname... : If provided, one or more attributes of <varname>; these attributes will also be converted to the specified type"
    echo ""
    echo "The following are optional arguments:"
    echo "[-m missval]: Change the missing_value and _FillValue attributes to <missval>."
    echo "              This will also change any missing data values to <missval>,"
    echo "              BUT ONLY IF _FillValue IS SET BEFORE RUNNING THIS SCRIPT!"
    echo "              IMPORTANT NOTE: If no -m option is specified, then we delete the"
    echo "              missing_value and _FillValue attributes of <varname>."
    exit 1
}

# -----------------------------
# Set default values
# -----------------------------
missval=

# -----------------------------
# Handle command-line arguments
# -----------------------------

while getopts m: opt
do
    case $opt in
	m) missval=$OPTARG;;
	\?) Usage
    esac
done

# shift off the arguments we read with getopts:
shift `expr $OPTIND - 1`

if [[ $# -lt 4 ]]; then
    Usage
fi

infile=$1
varname=$2
outfile=$3
type=$4
shift 4    # shift off those three arguments

# -----------------------------
# Parse type
# -----------------------------

case $type in
    byte) type_code=b;;
    short) type_code=s;;
    int) type_code=i;;
    float) type_code=f;;
    double) type_code=d;;
    *) 
	echo "ERROR: Type must be one of 'byte', 'short', 'int', 'float', or 'double'"
	exit 1
	;;
esac

# -----------------------------
# If a missing data value is given, set missing_value and _FillValue;
# otherwise, delete missing_value and _FillValue attributes
# -----------------------------

if [ -n "$missval" ]; then
    ncatted -a missing_value,$varname,o,$type_code,$missval -a _FillValue,$varname,o,$type_code,$missval $infile $outfile.tmp.$$
else
    ncatted -a missing_value,$varname,d,, -a _FillValue,$varname,d,, $infile $outfile.tmp.$$
fi

# -----------------------------
# Convert data to desired type
# -----------------------------

ncap2 -s "$varname=$type($varname)" $outfile.tmp.$$ $outfile
rm $outfile.tmp.$$

# -----------------------------
# Change other attributes to the specified type, if desired
# -----------------------------

while (( $# > 0 )); do  # loop through remaining command-line arguments
    att=$1
    ncap2 -A -s "${varname}@$att = $type(${varname}@$att)" $outfile $outfile
    shift
done
    