#!/bin/bash

# Prints contents of all files in this directory and subdirectories. First
# prints the file name, then prints its contents.

# With no arguments, uses the current directory. With one or more arguments,
# prints contents of all of those directories.

if [ $# -ge 1 ]; then
    mydir="$@"
else
    mydir=.
fi

find $mydir -type f -exec echo "--- {} ---" \; -exec cat {} \;
