#!/bin/bash

if [ -z $1 ]; then
  echo "ERROR: usage is qpeek JOBID"
  exit 1
fi

JOBID=$1

rem_host=`qstat -f $JOBID | grep exec_host | cut -d '=' -f 2 | cut -d '/' -f 1`

ssh -t ${rem_host} "tail -f /var/spool/pbs/spool/${JOBID}.chadmin1.OU"

