#!/bin/bash

# Bill Sacks
# 1-3-11

# List all tags in the tag directory corresponding to the current
# URL. If the current URL is within the trunk or a branch, then it
# lists the tags in the corresponding trunk_tags or branch_tags
# directory. If the current URL is itself within trunk_tags or some
# branch's branch_tags, then it lists all "siblings" of this tag.
#
# If a URL is given, then use the given URL rather than the URL of the
# current directory

# ----------------------------------------------------------------------
# LOCAL FUNCTIONS DEFINED HERE
# ----------------------------------------------------------------------

function Usage {
    progname=`basename $0`
    echo "Usage: $progname [-h] [-u url]"
    echo ""
    echo "This script lists all tags in the tag directory corresponding to the current URL."
    echo ""
    echo "If -u URL is given, then use that url, otherwise use the URL of the current directory"
    echo ""
    echo "The following are optional arguments:"
    echo "[-h]: Print this help message and exit"
    echo "[-u URL]: List all tags in the tag directory corresponding to this URL"
    echo "          (if not given, use the URL of the current directory)"
    echo ""
}

# ----------------------------------------------------------------------
# BEGIN MAIN SCRIPT
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Handle command-line arguments
# ----------------------------------------------------------------------

# define default values:
source_url=""

while getopts hu: opt; do
    case $opt in
	h) Usage; exit;;
	u) source_url=$OPTARG;;
	\?) Usage; exit 1
    esac
done

# shift off the arguments we read with getopts:
shift `expr $OPTIND - 1`

if [[ $# -ne 0 ]]; then
    Usage
    exit 1
fi

# ----------------------------------------------------------------------
# If URL isn't specified, get current URL from svn
# ----------------------------------------------------------------------

if [[ -z "$source_url" ]]; then
    source_url=`svn-url`
    if [ $? -ne 0 ]; then
	# for non-zero return value, source_url holds the error string
	echo $source_url
	exit 1
    fi
fi

# ----------------------------------------------------------------------
# Get directory of tags corresponding to this URL
# ----------------------------------------------------------------------

main_and_tags=`svn-get_root_urls $source_url`
tags=`echo $main_and_tags | awk '{print $2}'`

svn ls $tags