#!/bin/bash

# Bill Sacks
# 2-23-12

# This script shows all files that have changed in both of two svn paths, relative to a common ancestor
# This is useful to see potential merge conflicts. 
# For example, if we have a branch tag https://svn-ccsm-models.cgd.ucar.edu/clm2/branch_tags/dynlu_tags/dynlu04_clm4_0_37 (up to date with clm4_0_37),
# and we want to merge it up to clm4_0_40, then we could do:
# svn-possible_conflicts https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_0_37 https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_0_40 https://svn-ccsm-models.cgd.ucar.edu/clm2/branch_tags/dynlu_tags/dynlu04_clm4_0_37

# Adapted from
# http://stackoverflow.com/questions/4448500/in-subversion-list-files-that-have-changed-on-the-trunk-but-not-on-a-branch-and

# 7-9-12: Could I get similar or more accurate results by doing svn
# merge --dry-run and looking for 'G' and 'C'???

if [ $# -ne 3 ]; then
    echo "Usage: svn-possible_conflicts ancestor_path path1 path2"
    echo "where ancestor is the svn path of a common ancestor,"
    echo "and path1 and path2 are the svn paths that you want to compare"
    exit 1
fi

ancestor_path=$1
path1=$2
path2=$3

# getting the changed file list in path1
svn diff --summarize $ancestor_path $path1 > changes-path1.full.$$
echo "--- CHANGES IN PATH 1 ---"
cat changes-path1.full.$$
echo ""
# this sed command removes the status columns, which might cause uniq to fail identifying equal files
sed -e 's/.......//' changes-path1.full.$$ > changes-path1.$$
# find lines that do not have a space in the first column
# (this generally indicates changes to the file contents)
grep '^[^ ]' changes-path1.full.$$ > changes-path1.full.contentChange.$$
sed -e 's/.......//' changes-path1.full.contentChange.$$ > changes-path1.contentChange.$$

# getting the changed file list in path2
svn diff --summarize $ancestor_path $path2 > changes-path2.full.$$
echo "--- CHANGES IN PATH 2 ---"
cat changes-path2.full.$$
echo ""
sed -e 's/.......//' changes-path2.full.$$ > changes-path2.$$
grep '^[^ ]' changes-path2.full.$$ > changes-path2.full.contentChange.$$
sed -e 's/.......//' changes-path2.full.contentChange.$$ > changes-path2.contentChange.$$

# display the files which changed in both paths
echo "--- POSSIBLE CONFLICTS ---"
sort changes-path1.$$ changes-path2.$$ | uniq -d
echo ""
echo "--- POSSIBLE CONFLICTS: STATUS CHARACTER IN FIRST COLUMN IN BOTH PATHS ---"
sort changes-path1.contentChange.$$ changes-path2.contentChange.$$ | uniq -d


rm changes-path1.full.$$ changes-path2.full.$$ changes-path1.$$ changes-path2.$$
rm changes-path1.full.contentChange.$$ changes-path2.full.contentChange.$$ changes-path1.contentChange.$$ changes-path2.contentChange.$$