#!/bin/bash

# Bill Sacks
# 10-21-11

# This script echoes the svn URL of the current directory.
# If there is an error, the error string is echoed and the return
# value is non-zero
    
# Get the line containing the URL from svn info:
my_url=`svn info | grep "^URL: "`
if [ $? -ne 0 ]; then
    echo "ERROR trying to obtain URL from svn info"
    exit 1
fi
    
# get rid of the leading "URL: ", so we just have the URL itself
my_url=${my_url/URL: /}

echo $my_url
