#!/bin/bash

# Bill Sacks
# Oct 25, 2012

# This script shows you the changes since the last tag.

# In order to reuse code, it does this by using svn-make_cesm_tag with
# the "dryrun" flag. This means that some extra stuff is printed that
# can be ignored.

# ----------------------------------------------------------------------
# LOCAL FUNCTIONS DEFINED HERE
# ----------------------------------------------------------------------

function Usage {
    progname=`basename $0`
    echo "Usage: $progname [-h] [-u url]"
    echo "Shows changes made since the last tag, and other useful information"
    echo "If -u is given, use the given url, otherwise use svn url of current directory"
    echo ""
    echo "The following are optional arguments:"
    echo "[-h]: Print this help message and exit"
    echo ""
    echo "[-u URL]: Use the specified URL to find the appropriate trunk/trunk_tags"
    echo "          or branch/branch_tags directories"
    echo "          (If not given, uses the URL of the current directory)"
    echo ""
}
    

# ----------------------------------------------------------------------
# BEGIN MAIN SCRIPT
# ----------------------------------------------------------------------

url=""
while getopts hu: opt; do
    case $opt in
	h) Usage; exit;;
	u) url=$OPTARG;;
	\?) Usage; exit 1
    esac
done

args="-d -m 'testing' XXX_DUMMY_TAG_XXX"
if [[ -n "$url" ]]; then
    args="-u $url $args"
fi

svn-make_cesm_tag $args

