#!/bin/bash

# Move any files / directories in the current directory that are more
# than N days old into a new folder called "trash".
#
# The point of this is: Then we can delete these old files /
# directories (after reviewing them).
#
# Usage: trash_old N

# ----------------------------------------------------------------------
# Set some parameters here
# ----------------------------------------------------------------------

# name (including path, if relevant) of trash directory
trashdir=trash

# ----------------------------------------------------------------------
# Done setting parameters
# ----------------------------------------------------------------------


function Usage {
    echo "Usage: $0 N"
    echo "N: files / directories at least N days old are moved to trash"
    echo ""
    echo "Move any files / directories in the current directory that are more"
    echo "than N days old into a new folder called 'trash'"
    echo ""
}

if [ $# -ne 1 ]; then
    Usage
    exit 1
fi

n=$1

if [ -e $trashdir ]; then
    echo "trash already exists; please remove or rename then re-run this script"
    exit 1
fi
mkdir $trashdir

oldfiles=`find * -prune -mtime +$n`
ls -Gdlrt $oldfiles
mv $oldfiles $trashdir

