#!/bin/bash

# Move any files / directories in the current directory that have not
# been accessed in more than N days and are owned by the current user
# into a new folder called "trash_$USER".
#
# The point of this is: Then we can delete these old files /
# directories (after reviewing them).
#
# Usage: trash_old N

# ----------------------------------------------------------------------
# Set some parameters here
# ----------------------------------------------------------------------

# name (including path, if relevant) of trash directory
trashdir=trash_${USER}

# ----------------------------------------------------------------------
# Done setting parameters
# ----------------------------------------------------------------------


function Usage {
    echo "Usage: $0 N"
    echo "N: files / directories at least N days old are moved to trash"
    echo ""
    echo "Move any files / directories in the current directory that are more than N"
    echo "days old and owned by the current user into a new folder called '${trashdir}'"
    echo ""
}

if [ $# -ne 1 ]; then
    Usage
    exit 1
fi

n=$1

if [ -e $trashdir ]; then
    echo "${trashdir} already exists; please remove or rename then re-run this script"
    exit 1
fi
mkdir $trashdir

oldfiles=`find * -maxdepth 0 -user sacks -atime +$n`
ls -Gdlrt $oldfiles
mv $oldfiles $trashdir

